<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRMS.Contracts\HRMS.Contracts.csproj" />
    <ProjectReference Include="..\HRMS.Leave.Domain\HRMS.Leave.Domain.csproj" />
  </ItemGroup>

</Project>
